# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e28cc57520f9f283e815e0fee63d9cf1"
name = "journal-shop-dev"
application_url = "http://localhost:3000"
embedded = false

[webhooks]
api_version = "2026-01"

[access_scopes]
scopes = "read_products,write_products,read_inventory,write_inventory,read_orders,write_orders,read_customers"
use_legacy_install_flow = false

[auth]
redirect_urls = [ "http://localhost:3000/api/auth" ]
